### ISSUE TITLE
2.5.3 LAG

### ISSUE THREAD

**Issue by Evolvee** [Evolvee/EvolvePWPUI-ClassicTBC#31]
fps spike issues and drops since the new patch

no idea why

**Comment by XyzKangUI** [comment]
I've experienced no lags since 2.5.3, but not using your addons so who knows what causes it. You could try use bugsack+buggrabber to see if you have any issue. At first sight on your TextureScript I discovered a taint. You need to make `TextStatusBar_UpdateTextString ` a local function and use hooksecurefunc.

**Comment by Evolvee** [comment]
Thx i will check it. I have no lua errors with buggrab.

**Comment by Evolvee** [comment]
> I've experienced no lags since 2.5.3, but not using your addons so who knows what causes it. You could try use bugsack+buggrabber to see if you have any issue. At first sight on your TextureScript I discovered a taint. You need to make `TextStatusBar_UpdateTextString ` a local function and use hooksecurefunc. 

Just tested it and there is no difference.

**Comment by Evolvee** [comment]
![unknown-25.png](https://user-images.githubusercontent.com/1942409/150631348-1a65193b-6801-4daa-b5ba-626034e3f2ae.png)

**Comment by Evolvee** [comment]
It seems to be the game itself thats lagging, not my addons... Shit company probably fucked the client as usual without making any changelogs.

**Comment by XyzKangUI** [comment]
> > I've experienced no lags since 2.5.3, but not using your addons so who knows what causes it. You could try use bugsack+buggrabber to see if you have any issue. At first sight on your TextureScript I discovered a taint. You need to make `TextStatusBar_UpdateTextString ` a local function and use hooksecurefunc.
> 
> Just tested it and there is no difference.

The only difference is that it shouldn't taint. I used your addon (with taint) now and it instantly pops this in arena: 
`1/22 18:55:48.949  Global variable TextStatusBar_UpdateTextString tainted by TextureScript - Interface\AddOns\TextureScript\TextureScript.lua:138
1/22 18:55:48.949  Execution tainted by TextureScript while reading TextStatusBar_UpdateTextString - Interface\FrameXML\UnitFrame.lua:718
1/22 18:55:48.949      UnitFrameManaBar_Update()
1/22 18:55:48.949      Interface\FrameXML\UnitFrame.lua:185 UnitFrame_Update()
1/22 18:55:48.949      Interface\AddOns\Blizzard_ArenaUI\Blizzard_ArenaUI.lua:152 ArenaEnemyFrame_UpdatePlayer()
1/22 18:55:48.949      Interface\AddOns\Blizzard_ArenaUI\Blizzard_ArenaUI.lua:218
1/22 18:55:48.949  An action was blocked in combat because of taint from TextureScript - ArenaEnemyFrame2:SetPoint()
1/22 18:55:48.949      Interface\AddOns\Blizzard_ArenaUI\Blizzard_ArenaUI.lua:174 ArenaEnemyFrame_UpdatePlayer()
1/22 18:55:48.949      Interface\AddOns\Blizzard_ArenaUI\Blizzard_ArenaUI.lua:218
1/22 18:55:48.949  An action was blocked in combat because of taint from TextureScript - ArenaEnemyFrames:Hide()
1/22 18:55:48.949      Interface\AddOns\Blizzard_ArenaUI\Blizzard_ArenaUI.lua:96 ArenaEnemyFrames_UpdateVisible()
1/22 18:55:48.949      Interface\AddOns\Blizzard_ArenaUI\Blizzard_ArenaUI.lua:179 ArenaEnemyFrame_UpdatePlayer()
1/22 18:55:48.949      Interface\AddOns\Blizzard_ArenaUI\Blizzard_ArenaUI.lua:218
1/22 18:55:48.949  An action was blocked in combat because of taint from TextureScript - ArenaEnemyFrame2PetFrame:Hide()
1/22 18:55:48.949      Interface\AddOns\Blizzard_ArenaUI\Blizzard_ArenaUI.lua:318 ArenaEnemyFrame_UpdatePet()
1/22 18:55:48.949      Interface\AddOns\Blizzard_ArenaUI\Blizzard_ArenaUI.lua:228`

I read that many NA players had lag issues 1-2 days ago. So it could have been on blizzard's end. Btw they did add some new graphic settings.

**Comment by Evolvee** [comment]
Yes those are old errors that we didnt know how to solve - those arent causing the  fps issues. It was related to nameplates somehow, we never figured out what it is.

About the taint... it is a taint but it seems unlikely to matter in this case...  it's going to be doing the normal Blizzard function first instead of just the replaced one.
If one implementation is slower it would be the non-taint way though because it's doing the normal Blizzard function then immediately running the new one to overwrite what it just did. Taint is only bad if it actually leads to a problem like not being able to do something in combat and that would have been noticed by now...

**Comment by XyzKangUI** [comment]
Nah I didnt say it causes any fps issues at all. I only mentioned that your addon has a taint. Btw your nameplate implementation to hide totemplates can be achieved with Gladdy by setting alpha scale to 0 on unwanted totems. 

Also I've encountered that since 2.5.3 that some functions such as `CompactUnitFrame_UpdateName` are not loaded properly without putting them in OnEvent ADDON_LOADED first. I've tried ##OptionalDebs and ##Dependecies Blizzard_NamePlates, but they had no effect. Blizzard changed in 2.5.3 the way addons load, e.g. you can now just drop addons in your folder and /reload instead of restarting client. Since there is no documentation on their new change, I have 0 clue what they did.

**Comment by Evolvee** [comment]
> I only mentioned that your addon has a taint. Btw your nameplate implementation to hide totemplates can be achieved with Gladdy by setting alpha scale to 0 on unwanted totems.
> 


This was our very first attempt on achieving that behavior and it was not working good enough. Trust me, we tried from all possible angles. There was an issue with white alpha layer background still being visible and clickable.

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/150651219-fc12ba9a-bba8-4a6c-9dee-03a1b676cb90.png)

**Comment by XyzKangUI** [comment]
> > Btw your nameplate implementation to hide totemplates can be achieved with Gladdy by setting alpha scale to 0 on unwanted totems.
> 
> This was our very first attempt on achieving that behavior and it was not working good enough. Trust me, we tried from all possible angles. There was an issue with white alpha layer background still being visible and clickable.

Yep the white layer when you mouseover is the highlight texture that you can remove from gladdy. But indeed totems are still clickable, although I did not get that it was part of the concept you want.

**Comment by Evolvee** [comment]
I only wanted what I already had on 2.4.3 - hide all totem nameplates, their names and only show tremor totem (highlighted). 
The problem with the alpha "hackfix" would be that it was possible to select that totem via it which wouldnt be otherwise possible if the nameplate wasnt there at all - therefore sometimes Jebaiting me into targeting a wrong totem.

**Comment by XyzKangUI** [comment]
I see, makes sense about the jebait. Anyway, did you trace the source of your lag?

**Comment by Evolvee** [comment]
Nope, I tried to install new gpu drivers (since I still had the old Nvidia drivers from november 2020 as that was the last driver that didnt have the massive fps lagspike issues related to hardware mouse cursor). It did +- nothing. So next step is gonna be reparing the client... unfortunately I am kinda hesistant to do it because I dont want to lose all of my saved stuff like cvars, interface settings etc. as TONS of these things are saved server-side nowadays.

**Comment by XyzKangUI** [comment]
While testing your addon, without using Gladdy I got the following error.  It would be nice to add extra checks incase someone uses default arenaframes or that other arenaframe addon i forgot the name of. 

6x TextureScript\TextureScript.lua:1110: Cannot find a library instance of "Gladdy".
[string "=[C]"]: in function `error'
[string "@BugSack\Libs\LibStub\LibStub.lua"]:38: in function `LibStub'
[string "@TextureScript\TextureScript.lua"]:1110: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "Gladdy"."

But it is not possible to hide a nameplate itself, you can see with fstack that other totem nameplates are just showing. Gladdy and your addon both hide the visual element of it; "nameplate.UnitFrame".  This makes both addons prone to jebait clicking. 
![image](https://user-images.githubusercontent.com/94811434/150654705-5c025323-7117-4ce3-9c03-f2cc7221b829.png)


I believe the best way to avoid jebait clicks is by using "stacked nameplates" instead of "overlapped" nameplates as selectable under Interface Options. Although it doesnt look nice with snape trap, or overall :/  The only modification that gladdy would require is to remove the 0.25 alpha or so to not see that white highlight you mention in a screenshot earlier. 

` if (UnitIsUnit("mouseover", self.unitID) or UnitIsUnit("target", self.unitID)) then
        self.selectionHighlight:SetAlpha(.25) -- remove this
    else -- remove this
        self.selectionHighlight:SetAlpha(0)
    end`

I like your custom nameplateborder texture alot btw, its so clean without the level text. Moreover, I noticed that the cast icon is overlapping some other texture, blizzard quality of control. I think its the bordershield. 
![image](https://user-images.githubusercontent.com/94811434/150653422-081f1f76-d188-4730-a0a7-9d07b6bbc475.png)

Last thing said, the newly added graphic setting I mentioned earlier are under the "Resample quality". First this was set to "disabled". For me vertical sync always the game to feel unnatural. Changing directx might help as well. On some gpu's dx11 (legacy) seems better than dx12. You could try make a backup of your WTF folder, repair the client and then see if you still have issues. If not, then try with your backupped WTF to see if the issue is caused by that. 

I wish you goodluck!

**Comment by Evolvee** [comment]
> While testing your addon, without using Gladdy I got the following error. It would be nice to add extra checks incase someone uses default arenaframes or that other arenaframe addon i forgot the name of.

Yea there is a comment about it in TextureScript as well. The UI is not rly intended to work as a standalone addon, its more of a personal repo that is 1:1 of what I am using in the game


> You could try make a backup of your WTF folder, repair the client and then see if you still have issues. If not, then try with your backupped WTF to see if the issue is caused by that.

Yea the problem is that WTF folder doesnt contain all the UI/Client settings and there doesnt seem to be a way to export them currently.
